### ISSUE TITLE
Prophecy List in Main

### ISSUE THREAD

**Issue by rimmer** [rimmer/My-Horoskope#10]
![Propecy list](https://user-images.githubusercontent.com/1504642/87470557-38f2aa00-c61d-11ea-988a-401bb5dee172.jpg)

## Story
As a user, I would like to get prediction for different dimensions of my life.

## Brief
This is just a list with predictions. 

## Elements 
See the color coding on the preview:
🟥 By clicking the triangle the user is navigated to a user profile page _(TODO add a link to an issue here)_
🟨 For now we need **only the first icon**, that indicates the horoscope sight of the user (you can download all of them in SVG from Figma)
🟦 Instead of the text on the mock we'd sometimes show text prophecies, that will correspond with the situation (user choice, date etc). For now we will show it randomly from the pre-defined list in resources. 
Also, we can call those containers with text, value and progress bar *cards*.
🟢 Prediction values are floats from 0.1 to 9.9

## Acceptance criteria
1. After user sign up, they are navigated to the main screen (which must be created and will contain this prophecy list) 
2. Cards pick up values from the database (including the progress bars)
3. The icon with the sight is corresponding with user birth date

**Comment by rimmer** [comment]
Addressing the question from @bgoncharuck regarding the text: shall we generate texts or use ones from storage?
There are two types of texts 
1. Just indicating what is influencing the prediction
2. A useful hint for the user in a form of a suggestion.

We omit the fist one for the present, because we do not have understanding how they are calculated.
And we do would not be generating the second, we will be using predefined resources.

**Comment by bgoncharuck** [comment]
https://github.com/rimmer/my_prophet/issues/12 I'm adding new model and entity

**Comment by bgoncharuck** [comment]
Some variables cannot be picked out from the string.
![Screenshot_20200716_190031](https://user-images.githubusercontent.com/25586948/87694381-cc9bb600-c796-11ea-88ce-fc04338608ac.png)

**Comment by bgoncharuck** [comment]
variables were picked thanks to MutableWrapper.

**Comment by rimmer** [comment]
> variables were picked thanks to MutableWrapper.

Not sure it's fully clear what variables :)

**Comment by bgoncharuck** [comment]
![Rectangle 73](https://user-images.githubusercontent.com/25586948/87944331-ee9f7c00-caa7-11ea-8e0b-f35c074b086f.png)

**Comment by bgoncharuck** [comment]
![Screenshot_20200720_164328](https://user-images.githubusercontent.com/25586948/87944569-3f16d980-caa8-11ea-9943-df929397d1b3.png)
