### ISSUE TITLE
User feelings poll

### ISSUE THREAD

**Issue by rimmer** [rimmer/My-Horoskope#11]
![poll-request_LI](https://user-images.githubusercontent.com/68290903/87697370-4b422480-c792-11ea-8729-97890badb311.png) 
![image](https://user-images.githubusercontent.com/68290903/87978325-86b15b80-cad0-11ea-8e32-b91981f558aa.png)

### Story
As a user, I would like to set evaluation data for my future predictions.

### Brief
After rolling the screen user can see the scale of avaluation personal`s feeling during a day. This scale corresponds to bar cards, describen in[Prophecy List in Main #10](https://github.com/rimmer/my_prophet/issues/10).

### Use Case

- [ ] Scenario 1:

1. User stays at one of two tabs, calls `Простой` (the Tab is pre-selected)
2. User sees the scale with a parameter `Настроение`, wher one can choose the evaluation index for its own mood from 1 till 6 by marking the accurate meaning in a range. By defoult each paramrter is preselected by middle value (3 points). User can change the value or leave as it is.
3. User clicks button `Уточнить прогноз`.
**Result**: _**The following window collapsed the next text appears instead (with a standart beackground colour)**: "Спасибо! Эти данные помогут системе ближе с Вами познакомиться". 

- [ ] Alternative scenario:

1. User goes to a tab `Расширенный`.
2. User sees the following parameters, each of them has an evaluation scale with a scale:

- Настроение
- Продуктивность
- Отношения
- Саморазвитие
- Физическая активность

3a. By defoult each paramrter is preselected by middle value (3 points). User can change the value or leave as it is. 
3b. User marks criteria to evaluate a well-being or saves defoult parametrs. 
3c. User click the button `Уточнить прогноз` without settling all the Parametrs.
**Result**: : _**The following window collapsed the next text appears instead (with a standart beackground colour)**: "Спасибо! Эти данные помогут системе ближе с Вами познакомиться".

**Comment by bgoncharuck** [comment]
(Здоровье) -> Здоровье, так і лишається

( ) -> Удовлетворенность 

(Амбиции) -> Уважение

(Внутренняя энергия) -> Внутренняя сила

( ) -> Творческий потенциал

(Интелект) -> Интеллект

(Удача) -> Связь с миром -> залишити Удача

—————————-
(Внешние фактор) -> забрати

**Comment by bgoncharuck** [comment]
**Удовлетворенность**

1. _Насколько вы довольны этим днем?_

2. Были ли вы циничным?
3. Как много вы сделали для партнера?
4. Как сильно вы жалели себя?
5. Довольны ли вы своим партнером?

**Comment by bgoncharuck** [comment]
**Уважение**

1. _Этот день был полезным для окружающих?_

2. Были ли вы пренебрежительные к окружающим?
3. Как старательно вы работали?
4. Вы были справедливы?
5. Успели ли вы сделать то, что хотели?

**Comment by bgoncharuck** [comment]
**Здоровье**

1. _Вы чувствовали себя здоровым и сильным?_
(Це треба якось перефразувати, допоможіть)

2. Чувствовали ли вы страх?
3. Насколько бодрым вы были?
4. Делали зарядку утром?
5. Правильно ли питались?

**Comment by bgoncharuck** [comment]
**Внутренняя сила**

1. _Вы чувствовали любовь?_

2. Как много времени провели с друзьями?
3. Слышали ли вы похвалу?
4. Вы чувствовали гнев?
5. Вы узнали что-то новое?

**Comment by bgoncharuck** [comment]
**Творческий потенциал**

1. _Были ли у вас новые идеи?_

2. Как много вы критиковали других?
3. Вы обижались на что то?
4. Вы планировали этот день?
5. Были ссоры?

**Comment by bgoncharuck** [comment]
**Интеллект**

1. _Были ли вы примером для других?_

2. Как много времени вы уделили искусству?
3. Научили ли вы других чему-то новому?
4. Чувствовали ли вы презрение?
5. Как много времени вы уделили размышлениям, медитации или молитве?

**Comment by bgoncharuck** [comment]
**Удача**

1. _Вы благодарны за этот день?_

2. Пытались ли вы сделать этот мир лучше?
3. Вы следовали собственным принципам?
4. Как много вы помогали нуждающимся?
5. Простили ли вы других?

**Comment by bgoncharuck** [comment]
Перші питання будуть в простому варіанті, всі інші в розширеному.
