### ISSUE TITLE
Prophecy Entity

### ISSUE THREAD

**Issue by bgoncharuck** [rimmer/My-Horoskope#12]
I'm adding new model and entity.

ChangeModel:
```
@JsonSerializable()
class ChangeModel {
  final String changeIconName;
  final String changeText;
  final double value;
}
```
ProphecyEntity:
```
@JsonSerializable()
class ProphecyEntity {
  ProphecyModel model;
  List<ChangeModel> changes;
}
```

**Comment by rimmer** [comment]
It was not necessary to create an issue for that. It was sufficient to create a pull request that will be referencing #10. This issue does not contain any useful information, just a comment regarding you changes in scope of #10 . 

I mean, its fine, but it was not required :)

**Comment by bgoncharuck** [comment]
Model is immutable object that can be used in different modules.
Data is mutable object that is used to save information in base or show it in screen.
Data can contain several models, other data objects or any other information.
Data objects can have mutable fields and change during program runtime.

![data_model](https://user-images.githubusercontent.com/25586948/87574262-d3fb8a80-c6d6-11ea-9490-60f56995de4f.jpg)
