### ISSUE TITLE
Implement algorythm for calculating user's predictions

### ISSUE THREAD

**Issue by bgoncharuck** [rimmer/My-Horoskope#15]
Minimal value: 20 points
Maximum value: 95 points
Avaible values: 95-20 = 75 points

**Const** birth part, by _numerology_ and _astrology_: 20 points
**Dynamic** part, by _chakras calulation_ and/or _planet position_: 20 points
**Dynamic** part, by user choises in questions: 35 points

User birth is a constant seed, 
The value added to seeed, depending from day/month/year since approach, it need calculation,
The value added from user poll,

**How to correctly store user choises?**
Should we save only one month values, and clean any other?

**UPD (12/08/20): 
According to new algorithm, prediction`s indicators depend on user`s poll indicators in a following way:**

Удача - Настроение
Внутренняя сила - Отношения
Самочувствие - Физическая активность
Амбиции - Продуктивность
Интеллект - Саморазвитие

**Comment by bbks** [comment]
Итак. Ничего, что я не по-антимонгольски пишу? Надеюсь что ничего. По по воду подсчета:
Предложение мое следующее:
1. За основу берем хешфункцию и бета распределение, получаем число от 3 до 9.5
2. Считаем корректировки по результатам выбора пользователя и вностим корректировки на сегодня и на следующие дни по следующей логике:
     Вариант а, "простой", там где только настроенеие) Настроение меняет все показатели (кроме удачи) на сегодня в пределах +/- 10% , на завтра +/- 5% и на послезавтра +/- 2%, но тут стоит думаю ввенсти элемент хаотичности, что бы при плохом настроение показатели падали, а при хорошем - подымались, но что бы была небольшая вероятность и обратного результата. Как это может работать. Например, при настроении 1, внутренняя сила скорее всего сместитья на -10%, но может и на -5, и совсем редко на +5 и почти никогда на +10, а при настроении 3, она должна остаться на прежнем уровне или с небольшой вероятносью сместаиться н в пределах +/- 5 и совсем редко когда уйти на +/-10.
     Вариант б, "расширенный", тут немного сложнее, но логика та же. Кажый показатель меняет зависящие от него предсказания в пределах 8/4/2% (сегодня/завтра/послезавтра) и тоже с вероятностью отклонения. Вот что как и на что влияет: Настроение на все, кроме удачи, Продуктивность на Амбиции и Интеллект, Отношения на Самочуствие и Отношения с Окружением, Саморазвитие, на Амбиции и Внутреннюю силу, и Физическая Активность, на Внутреннюю Силу, Самочувствие и Интеллект. Таким образом, каждое предсказание может сместиться максимально на 24% но не должно, тем не мение быть ниже 2 балов или выше 10. 
Вангую много ифов. и елсе ифоф.
