### ISSUE TITLE
Bug: The cursor moves back one step as you enter gender

### ISSUE THREAD

**Issue by olena-euglena** [rimmer/My-Horoskope#35]
Registration screen
Now: After entering the gender, the cursor is moved one step back - to the input field of the year of birth

Expected: move the cursor to the country input field

**Comment by bgoncharuck** [comment]
onPointerUp: (_) {
          FocusScopeNode currentFocus = FocusScope.of(context);
          if (!currentFocus.hasPrimaryFocus &&
              currentFocus.focusedChild != null) {
            currentFocus.focusedChild.unfocus();
          }
        },
