### ISSUE TITLE
Змінити повідомленпя про необхідність погодження з умовами

### ISSUE THREAD

**Issue by olena-euglena** [rimmer/My-Horoskope#36]
Екран реєстрації

Наразі: При незаповненні чекбоксу з умовами політики конфіденційності з'являється повідомлення: "Вы не приняли условий". Потрібен колл ту екшн окрім пояснення помилки
 ТРЕБА ПОДУМАТИ НАД ОПТИМАЛЬНИМ ВАРІАНТОМ
(Цей варіант не дуже) Потрібно: "Поставьте галочку напротив "я принимаю условия", чтобы принять условия политики конфиденциальности и пользовательского соглашения"

**Comment by bgoncharuck** [comment]
Ознакомьтесь с пользовательским соглашением и политикой конфиденциальности

**Comment by olena-euglena** [comment]
> Ознакомьтесь с пользовательским соглашением и политикой конфиденциальности

Да, мабуть, хай буде
