### ISSUE TITLE
Bug: The app should name its name on the app icon

### ISSUE THREAD

**Issue by rimmer** [rimmer/My-Horoskope#38]
### Platform
Android
### Repro steps
1. Install the app
2. Open app list

### Problem 
The app name is "app"

### Expected result
The app name should be "My Prophet" or similar according to the app locale

### Screenshot
![Screenshot_1608152165](https://user-images.githubusercontent.com/1504642/102405621-bb76ff80-3fe9-11eb-941b-7eedd088ed07.png)

**Comment by bgoncharuck** [comment]
The bug was already discussed, but I will fix it

**Comment by bgoncharuck** [comment]
Stop using fat apk, you cant choose a name other than package name, without using app_bundle and play market/app store
