### ISSUE TITLE
Register screen

### ISSUE THREAD

**Issue by rimmer** [rimmer/My-Horoskope#4]
As a user I would like to have my prediction as precise as possible, so I would like to give the app as much data as required.

## UI
![Login/Register](https://user-images.githubusercontent.com/1504642/86542143-30aab880-bf13-11ea-9c0d-de4853f71ee2.jpg)
## Fields
* **Name** - might be any string, we might limit it to 100 symbols
* **Birthdate** - would be nice to have date/time picker for it. When picked data **and** time, autofill *birthtime* as well
* **Gender at birth** - might be a picker/radio; this one will be improved by designer I hope; I suppose, must be a choice of three options (Male/Female/Other)
* **Country of bitrth** - just a string, limited to 50 symbols. I dont think we should maintain a list of countries at this point.
* **Place of birth** -a string, limited to 100 symbols. I dont think we should maintain a list of countries at this point.
### Validation rules
* *Name* and *date of birth* are mandatory.  Others are not. 
* *date of birth* accepts date from the date/time picker, however might be entered manually (the format should be provided in a field hint and should follow locale rules)
* *Gender at birth* should be a choice of three options
* *Country of bitrth* string, limited to 50 symbols
* *Place of birth** a string, limited to 100 symbols.

#### Figma export
Please note, that you can use Figma Export tool to export any element you would need 
![Export](https://user-images.githubusercontent.com/1504642/86542176-9b5bf400-bf13-11ea-8524-6ff238ba4bcb.png)

Please also note similar form will be used in User Settings page (TODO: add link to the corresponding issue).

**Comment by bgoncharuck** [comment]
![Frame 244](https://user-images.githubusercontent.com/25586948/86816482-88206400-c08c-11ea-9c98-ad5640d1a582.png)
