### ISSUE TITLE
Bug: Crash with newly created user

### ISSUE THREAD

**Issue by rimmer** [rimmer/My-Horoskope#41]
### Platform
Android
### Repro steps
1. Uninstall app or cleap all data
2. Launch the app
3. Fill up Login form
4. Observe the crash (see screenshot)
### Expected
No crash
### Screehshot
![Screenshot_1608152556](https://user-images.githubusercontent.com/1504642/102406782-5fad7600-3feb-11eb-8a2e-8a37ad6abe73.png)
### Crashlog
![image](https://user-images.githubusercontent.com/1504642/102406982-a9965c00-3feb-11eb-9925-9189aded5c8e.png)

**Comment by bgoncharuck** [comment]
Done, add one string to packages/data/platform/prophecy_to_show_storage_flutter/lib/src/json_storage.dart
method read, on exception, add one line before writting
`
catch (_) {
      print("Error was catched when reading $_fileName file: $_");
`
      **_ep = EnabledProphecies();**
`
      this.write();
    }
`
