### ISSUE TITLE
Додати обмеження на введення року народження

### ISSUE THREAD

**Issue by olena-euglena** [rimmer/My-Horoskope#42]
Екран реєстрації:
Наразі: відсутні обмеження га введення числових значень року

Потрібно: встановити обмеження на найдавнішу дату, а також для дітей віком молодшим за 12 років
Найнижчий можливий показник для введення року - 1920
Найвищий - 2008

**Comment by bgoncharuck** [comment]
Done, but I dont understand why

**Comment by bgoncharuck** [comment]
I will do it, but I dont understand why

**Comment by olena-euglena** [comment]
Бо наразі можна ввести 1256 рік і аплікація дасть прогноз. Це нонсенс і виглядає ніби ми на надто дбаємо про реалістичність передбачень. А про 12 років мінімальний вік - питання контраверсійне, тут точки зору розбіглись

**Comment by bgoncharuck** [comment]
Я особисто не бачу нічого поганого в цьому.
Але як хочете

**Comment by olena-euglena** [comment]
Якщо зі сталою величиною проблема, тоді ок, обмеження на найменший вік - недоцільне. Але обмеження на найстарішого я б залишила
