### ISSUE TITLE
Виведення і повторення передбачення 

### ISSUE THREAD

**Issue by olena-euglena** [rimmer/My-Horoskope#49]
Проблема

Передбачення виводиться не лише на поточний день, а й на будь-яку дату у майбутньому. При цьому передбачення зацикленні і повторюються.
![Screenshot_20201219-125117.jpg](https://user-images.githubusercontent.com/68290903/102691431-72e75e00-4204-11eb-9bda-b0fee73c45ab.jpg)![Screenshot_20201219-125312.jpg](https://user-images.githubusercontent.com/68290903/102691432-75e24e80-4204-11eb-8510-26b064e4fb20.jpg)![Screenshot_20201219-125612.jpg](https://user-images.githubusercontent.com/68290903/102691434-7844a880-4204-11eb-9391-308cfdddeba6.jpg)

**Comment by bgoncharuck** [comment]
Вони і повинні "повторюватися", оскільки усі передбачення використовують теперішню дату Date.now()

Питання в тому, як воно показує його на інші дні, якщо стоїть перевірка на isToday

- - -

У мене не вийшло знайти цей баг на жодному пристрої.
Можете пояснити, як саме він виникнув, бо це означає що isToday не спрацював ,а тобто якісь пробелми або із часом на телефоні, або із seed-ом

**Comment by rimmer** [comment]
Закриваємо допоки зможемо відтворити
