### ISSUE TITLE
Змінити тип вводу для полів реєстрації

### ISSUE THREAD

**Issue by rimmer** [rimmer/My-Horoskope#50]
## Платформа
Android

## Опис
Потрібно щоб метод вводу пропонував писати слова з великої літери.
Наприклад, ім'я або країну.

## Відтворення
1. Запустити вперше або перейти на екран "Настройки профиля"
2. Спробувати ввести щось в поля
3. Метод вводу пропонує слова з маленької літери

## Очікуваний результат
Метод вводу пропонує писати слова з великої літери.

**Comment by bgoncharuck** [comment]
Це не контролюється Flutter-ом, а залежить від клавіатури користувача Android та її налаштувань, все що можна зробити - випадаюче вікно - https://pub.dev/packages/autocomplete_textfield , для якого потрібно буде звідкись брати данні.

Це точно баг?
