### ISSUE TITLE
Деякі елементи важко натискати

### ISSUE THREAD

**Issue by rimmer** [rimmer/My-Horoskope#57]
Платфома: Android

При натисканні на наступні контроли треба дуже точно попасти по контролу, інакше він не зпрацьовує:
1. Меню
2. Голосування
3. Календар

Бажаний результат:
Натискати легко з першого разу.

**Comment by bgoncharuck** [comment]
Changing every GestureDetector to FlatButton with this change to the ThemeData:

`    buttonTheme: ButtonThemeData(
      padding: EdgeInsets.all(0.0), //adds padding inside the button
      minWidth: 0, //wraps child's width
      height: 0,
    )`
    
Is solve this.
