### ISSUE TITLE
Cutted buttons in pop-ups

### ISSUE THREAD

**Issue by olena-euglena** [rimmer/My-Horoskope#70]
**Location:** Home screen
**Preactions:** Tap information buttons
**Device:** HUAWEI Mate 10 lite

![photo_2021-03-08_18-49-23](https://user-images.githubusercontent.com/68290903/111376533-d9fb9e00-869f-11eb-8b39-943d410dba74.jpg)

**Comment by bgoncharuck** [comment]
Closed in cards brunch with ListView and screen size part.
