### ISSUE TITLE
Integrate some of the Firebase Services

### ISSUE THREAD

**Issue by rimmer** [rimmer/My-Horoskope#79]
* Google Analytics (it reports through Firebase, just another name)
* [Crashlytics](https://firebase.flutter.dev/docs/crashlytics/overview/): would be nice to also [have all Flutter crashes](https://firebase.flutter.dev/docs/crashlytics/usage#handling-uncaught-errors) reported to Crashlytics
* Firebase In-App Messaging: preparation only
* Firebase Cloud Messaging : sending messages from Firebase console 

Please also add iOS app to Firebase Console as well
This might also require using mac, please contact @rimmer for the credentials for MacInCloud account

**Comment by bgoncharuck** [comment]
Google Analytics done (android)
Crashanalytics done (android)

**Comment by bgoncharuck** [comment]
firebase_in_app_messaging

Is in beta and crashes

**Comment by bgoncharuck** [comment]
https://flutteragency.com/how-to-deal-with-multidex-issue-in-flutter/

firebase_in_app_messaging works, with some warnings

**Comment by bgoncharuck** [comment]
Firebase In-App Messaging, preparation only: done
Firebase Cloud Messaging: done
