### ISSUE TITLE
Add full screen ads (Google Ads) into the cards flow

### ISSUE THREAD

**Issue by rimmer** [rimmer/My-Horoskope#83]
@bbks could you please add specify how should it look like

**Comment by bbks** [comment]
![image](https://user-images.githubusercontent.com/12209461/113878483-ec0dbf80-97b9-11eb-896f-c85bcd19f0dd.png)

**Comment by rimmer** [comment]
Commit c152d57bcba9c0dd1cdd47b4046e81fcad1bc247 also belongs to this issue
